fix = true

[lint]
extend-select = [
        "A",       # flake8-builtins
        "B",       # flake8-bugbear
        "C4",      # flake8-comprehensions
        "C90",     # mccabe
        "COM812",  # missing-trailing-comma
        "COM812",  # prohibited-trailing-comma
        "D",       # pycodestyle
        "E",       # Error
        "F",       # pyflakes
        "I",       # isort
        "ISC",     # flake8-implicit-str-concat
        "NPY201",  # numpy 2.0
        "PERF401", # manual-list-comprehension
        "PD",      # pandas vett
        "PGH",     # pygrep-hooks
        "Q",       # flake8-quotes
        "RUF",     # ruff
        "S",       # flake8-bandit
        "SIM",     # flake8-simplify
        "T10",     # flake8-debugger
        "TRY",     # tryceratops
        "UP",      # pyupgrade
        "W",       # Warning
        "YTT",     # flake8-2020
]
ignore = [
        # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
        "W191",
        "E111",
        "E114",
        "E117",
        "D206",
        "D300",
        ### Various undocumented-X
        "D100",
        "D101",
        "D102",
        "D103",
        "D104",
        "D105",
        "D106",
        "D107",
        # one-blank-line-before-class
        "D203",
        # multi-line-summary-second-line
        "D213",
        # ends-in-period
        "D400",
        # dashed-underline-after-section
        "D407",
        # ends-in-punctuation
        "D415",
        ###
        "Q000",
        "Q001",
        "Q002",
        "Q003",
        "COM812",
        "COM819",
        "ISC001",
        "ISC002",
        # raise-vanilla-args
        "TRY003",
        # blanket-type-ignore
        "PGH003",
        # assert
        "S101",
]

[format]
# Enable preview to get hugged parenthesis unwrapping and other nice surprises
# See https://github.com/jaraco/skeleton/pull/133#issuecomment-2239538373
preview = true
# https://docs.astral.sh/ruff/settings/#format_quote-style
quote-style = "double"
